security:
  oauth2:
    client:
      clientId: 185039559140-1s9csghbocbtme92qfnqs0rqm2si69ps.apps.googleusercontent.com
      clientSecret: sxpIfH4hFBNeWVHeeHX_IHPS
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false